name:                sparse-bitmaps
version:             0.1.0.0
github:              "zouroboros/sparse-bitmaps"
license:             MIT
author:              "Zouroboros"
maintainer:          "zouroboros@zoho.eu"
copyright:           "2018 Zouroboros"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/zouroboros/sparse-bitmaps#readme>

dependencies:
- base >= 4.7 && < 5
- JuicyPixels >= 3.2 && < 47
- vector >= 0.12 && < 0.13

library:
  source-dirs: src

executables:
  sparse-bitmaps-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sparse-bitmaps

tests:
  sparse-bitmaps-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sparse-bitmaps
    - hspec >= 2.5
